# Root directory of the model assets (for inference).
# In training, the model assets will be saved to {assets_root}/{model_name},
# and in inference, we load all the models from {assets_root}.
assets_root: model_assets
